<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Страница сотрудника</h1>

<table>
    <tr>
        <th>Email</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Role</th>
        <th>Client</th>
        <th>Sales plan</th>
        <th>Completed plan</th>
    </tr>
</table>
</body>
</html>